/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TTicketCodeRouteImport } from './routes/t.$ticketCode'
import { Route as StaffVerifyRouteImport } from './routes/staff.verify'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiCronExpireRouteImport } from './routes/api/cron/expire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTicketCodeRoute = TTicketCodeRouteImport.update({
  id: '/t/$ticketCode',
  path: '/t/$ticketCode',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVerifyRoute = StaffVerifyRouteImport.update({
  id: '/staff/verify',
  path: '/staff/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExpireRoute = ApiCronExpireRouteImport.update({
  id: '/api/cron/expire',
  path: '/api/cron/expire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/e/$slug': typeof ESlugRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/t/$ticketCode': typeof TTicketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/expire': typeof ApiCronExpireRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/e/$slug': typeof ESlugRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/t/$ticketCode': typeof TTicketCodeRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/expire': typeof ApiCronExpireRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/e/$slug': typeof ESlugRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/t/$ticketCode': typeof TTicketCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/expire': typeof ApiCronExpireRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/e/$slug'
    | '/staff/verify'
    | '/t/$ticketCode'
    | '/admin/'
    | '/api/cron/expire'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/e/$slug'
    | '/staff/verify'
    | '/t/$ticketCode'
    | '/admin'
    | '/api/cron/expire'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/e/$slug'
    | '/staff/verify'
    | '/t/$ticketCode'
    | '/admin/'
    | '/api/cron/expire'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ESlugRoute: typeof ESlugRoute
  StaffVerifyRoute: typeof StaffVerifyRoute
  TTicketCodeRoute: typeof TTicketCodeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiCronExpireRoute: typeof ApiCronExpireRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$ticketCode': {
      id: '/t/$ticketCode'
      path: '/t/$ticketCode'
      fullPath: '/t/$ticketCode'
      preLoaderRoute: typeof TTicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/verify': {
      id: '/staff/verify'
      path: '/staff/verify'
      fullPath: '/staff/verify'
      preLoaderRoute: typeof StaffVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire': {
      id: '/api/cron/expire'
      path: '/api/cron/expire'
      fullPath: '/api/cron/expire'
      preLoaderRoute: typeof ApiCronExpireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ESlugRoute: ESlugRoute,
  StaffVerifyRoute: StaffVerifyRoute,
  TTicketCodeRoute: TTicketCodeRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiCronExpireRoute: ApiCronExpireRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
